import type { Metadata } from "next";
import { Inter, Fira_Code } from "next/font/google";
import "./globals.css";
import Navigation from '@/components/layout/Navigation';
import { ThemeToggle } from "@/components/theme-toggle";
import Footer from '@/components/layout/Footer';

// ⭐ Use generic variable names that never change
const primaryFont = Inter({
  variable: "--font-sans",  // ← Generic name (works with any font)
  subsets: ["latin"],
});

const codeFont = Fira_Code({
  variable: "--font-mono",  // ← Generic name (works with any font)
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Test Website",
  description: "Generated by AI Website Builder",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* ⭐ Prevent flash of wrong theme - runs before React */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const theme = localStorage.getItem('theme') || 'light';
                if (theme === 'dark') {
                  document.documentElement.classList.add('dark');
                }
              })();
            `,
          }}
        />
      </head>
      <body className={`${primaryFont.variable} ${codeFont.variable} antialiased`}>
        <Navigation />
        {children}

        {/* ⭐ Floating theme toggle - always visible */}
        <div className="fixed bottom-4 right-4 z-50 md:bottom-6 md:right-6">
          <ThemeToggle />
        </div>
              <Footer />
      </body>
    </html>
  );
}